apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: auto_run
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: auto_run
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - echo
            - greetings
            - from
            - kubernetesmaster
            image: busybox
            name: auto_run
            resources: {}
          restartPolicy: OnFailure
  schedule: '*\1 * * * *'
status: {}
