kind: Service
apiVersion: v1
metadata:
  name:  nginx-pod
spec:
  selector:
    app:  nginx-deployment-03
  type:  NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    NodePort: 80
    targetPort: nginx-port
    protocol: TCP