apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nginx-config-nfs
spec:
   storageClassName: config
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 500Mi
