apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 80
    nodePort: 31113
    protocol: TCP
  selector:
    app: nginx-deployment
