apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-01
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-dynamic-provisioning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-configuration-pvc-01
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nginx-configuration-dynamic-provisioning
