apiVersion: v1
kind: PersistentVolume
metadata:
   name: nginx-pv-nfs
   labels:
      type: local
spec:
   storageClassName: mannual
   capacity:
      storage: 3Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   hostPath:
      path: /mnt/nfs_share/nginx/html/
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: nginx-log-nfs
   labels:
      type: local
spec:
   storageClassName: logging
   capacity:
      storage: 2Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      path: /nginx-logs
      server: 172.16.12.24   
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: nginx-config-nfs
   labels:
      type: local
spec:
   storageClassName: config
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      path: /nginx-config
      server: 172.16.12.24
