apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
     app: nginx-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
        app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
          - name: nginx-port
            containerPort: 80
          volumeMounts:
            - name:  html
              mountPath: /usr/share/nginx/html
            - name: logs
              mountPath: /var/log/nginx 
#            - name: configure
#              mountPath: /etc/nginx
      volumes:
        - name:  html
          persistentVolumeClaim:
            claimName: nginx-pvc-nfs
        - name: logs
          persistentVolumeClaim:
            claimName: nginx-logclaim-nfs
#        - name: configure
#          persistentVolumeClaim:
#            claimName: nginx-config-nfs
